version: '3.3'

services:

  web:
    build:
      context: client
    image: devlibs-angular:latest
    ports:
      - '4200:4200'
      - '5858:5858'
      - '9229:9229'
    volumes:
      - ./api/data:/var/www/api/v1
    command: npm start

  api:
    build:
      context: api
    image: devlibs-api:latest
    ports:
      - '8080:80'
    volumes:
      - ./client:/usr/src/app
